### PR TITLE
gles linter

### PR DESCRIPTION
**Pull request by TimoBuskeKdab**
python script for checking gles compatibility of asset files
.dds .png .jpg

todo:
.gltf (mesh size)

required: ImageMagick

### CODE REVIEW

**Comment by lemirep** [comment]
The 3rd party linter code might not be compatible at all with python 3 though

**Comment by TimoBuskeKdab** [comment]
Okay, no problem. I just thought it's a good time to switch according to
https://pythonclock.org/
Actually the 3rd party stuff gave me errors using Python 2. But that should be fixable somehow I think.

**Comment by TimoBuskeKdab** [comment]
okay should work now on python 2 + 3

**Comment by mkrus** [comment]
needs some documentation, README.md with info on usage, and details of 3rd party code used...

**Pull request closed without merging**
