### PR TITLE
Use pregenerated images based on screen dpi

### PR DESCRIPTION
**Pull request by lemirep**
- Add python tool to pregenerate assets for various dpis
- Make StyledSlider/StyledSwitch use pregenerated assets

Task-Id: KUE-598

### CODE REVIEW

**Comment by lemirep** [comment]
Simplifies the code a bit, looks alright (not pixel perfect) on most platforms. Should fix the huge number of vertices in QtQuick

**Comment by mkrus** [comment]
Like the other patch, this UI is much too big on iPads
IMG_0015

Are both patches needed?

**Comment by lemirep** [comment]
I'd suggest we get this is even though it's not perfect on all platforms, gets us closers to not having 10000 vertices drawn by QtQuick. I suspect iPad doesn't report the correct dpi and chooses the wrong assets. Can't really fix test for this on my side but I'd assume someone with an ipad could fix that with minimal amount of code changes. Other patch from Nuno is not required.

**Comment by mkrus** [comment]
does it work on Android tablets with hidpi?

**Comment by lemirep** [comment]
DSC01405
Size is adequate on my phone

**Comment by mkrus** [comment]
While I agree it's good in fixing the rendering performance it also breaks scaling, I think because the dpi selection fails to take into account the `Screen.devicePixelRatio`. So on macOS (retina), and iPad, everything is way too large

**Comment by lemirep** [comment]
Ok given we've been stuck on this for almost 2 months, I'll let you take over an fix whatever needs to be for it to work properly on iPad as I can't test it here.

**Comment by lemirep** [comment]
Replaced by Mike's patch

**Pull request closed without merging**
